# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: NPM Install
      run: npm install
    - name: Install bower
      run: npm install -g bower
    - name: Install bower
      run: bower install
